In [1]:
import pandas as pd

In [2]:
from pathlib import Path

In [3]:
path_to_data = Path("../data")

In [4]:
path_to_csv = path_to_data / ("banknotesData.csv")

In [5]:
notes_df = pd.read_csv(path_to_csv)

In [6]:
notes_df.head()

,country,countryAbbr,currencyName,name,gender,billCount,profession,knownForBeingFirst,currentBillValue,propTotalBills,firstAppearanceDate,deathDate,appearanceDeathDiff,comments,hoverText,hasPortrait,id
0,Argentina,ARS,Argentinian Peso,Eva Perón,F,1.0,Activist,No,100,NaN,2012,1952,60.0,NaN,NaN,True,ARS_Evita
1,Argentina,ARS,Argentinian Peso,Julio Argentino Roca,M,1.0,Head of Gov't,No,100,NaN,1988,1914,74.0,NaN,NaN,True,ARS_Argentino
2,Argentina,ARS,Argentinian Peso,Domingo Faustino Sarmiento,M,1.0,Head of Gov't,No,50,NaN,1999,1888,111.0,NaN,NaN,True,ARS_Domingo
3,Argentina,ARS,Argentinian Peso,Juan Manuel de Rosas,M,1.0,Politician,No,20,NaN,1992,1877,115.0,NaN,NaN,True,ARS_Rosas
4,Argentina,ARS,Argentinian Peso,Manuel Belgrano,M,1.0,Founder,Yes,10,NaN,1970,1820,150.0,Came up with the first Argentine flag.,Designed first Argentine flag,True,ARS_Belgrano

In [7]:
notes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              279 non-null    object
 1   countryAbbr          279 non-null    object
 2   currencyName         279 non-null    object
 3   name                 279 non-null    object
 4   gender               279 non-null    object
 5   billCount            279 non-null    float64
 6   profession           279 non-null    object
 7   knownForBeingFirst   279 non-null    object
 8   currentBillValue     279 non-null    int64
 9   propTotalBills       59 non-null     float64
 10  firstAppearanceDate  279 non-null    int64
 11  deathDate            272 non-null    object
 12  appearanceDeathDiff  271 non-null    float64
 13  comments             119 non-null    object
 14  hoverText            89 non-null     object
 15  hasPortrait          279 non-null    bool
 16  id                   279 non-null    object
dtypes: bool(1), float64(3), int64(2), object(11)
memory usage: 35.3+ KB

In [8]:
notes_df.isna().sum().sum()

np.int64(585)

In [9]:
missing_deathDate = notes_df.copy(deep=True)

In [10]:
missing_deathDate = missing_deathDate[missing_deathDate["deathDate"].isna()]

In [11]:
missing_deathDate

,country,countryAbbr,currencyName,name,gender,billCount,profession,knownForBeingFirst,currentBillValue,propTotalBills,firstAppearanceDate,deathDate,appearanceDeathDiff,comments,hoverText,hasPortrait,id
13,Australia,AUD,Australian Dollar,Queen Elizabeth II,F,1.00,Monarch,No,5,0.11,1961,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
37,Bolivia,BOB,Boliviano,Genoveva Ríos,F,0.33,Other,No,20,NaN,2018,NaN,NaN,national hero,NaN,False,BOB_Rios
101,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,5,0.10,1963,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
102,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,10,0.34,1964,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
103,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,20,0.47,1970,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
104,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,50,0.09,1981,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
172,New Zealand,NZD,New Zealand dollar,Queen Elizabeth II,F,1.00,Monarch,No,20,0.16,1967,NaN,NaN,NaN,NaN,True,AUD_Elizabeth

In [12]:
missing_appearanceDeathDiff = notes_df.copy(deep=True)

In [13]:
missing_appearanceDeathDiff = missing_appearanceDeathDiff[missing_appearanceDeathDiff["appearanceDeathDiff"].isna()]

In [14]:
missing_appearanceDeathDiff

,country,countryAbbr,currencyName,name,gender,billCount,profession,knownForBeingFirst,currentBillValue,propTotalBills,firstAppearanceDate,deathDate,appearanceDeathDiff,comments,hoverText,hasPortrait,id
13,Australia,AUD,Australian Dollar,Queen Elizabeth II,F,1.00,Monarch,No,5,0.11,1961,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
37,Bolivia,BOB,Boliviano,Genoveva Ríos,F,0.33,Other,No,20,NaN,2018,NaN,NaN,national hero,NaN,False,BOB_Rios
46,Canada,CAD,Canadian Dollar,Queen Elizabeth II,F,1.00,Monarch,No,20,NaN,1935,-,NaN,NaN,NaN,True,AUD_Elizabeth
101,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,5,0.10,1963,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
102,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,10,0.34,1964,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
103,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,20,0.47,1970,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
104,England,GBP,pound,Queen Elizabeth II,F,0.50,Monarch,No,50,0.09,1981,NaN,NaN,NaN,NaN,True,AUD_Elizabeth
172,New Zealand,NZD,New Zealand dollar,Queen Elizabeth II,F,1.00,Monarch,No,20,0.16,1967,NaN,NaN,NaN,NaN,True,AUD_Elizabeth

In [15]:
notes_df.loc[notes_df["name"] == "Queen Elizabeth II", "deathDate"] = 2022

In [16]:
notes_df.loc[notes_df["name"] == "Genoveva Ríos", "deathDate"] = "unknown"

In [17]:
notes_df.isna().sum().sum()

np.int64(578)

In [18]:
notes_df["deathDate"] = pd.to_numeric(notes_df["deathDate"], errors="coerce").astype("Int64")

In [19]:
notes_df['deathDate'].isna().sum()

np.int64(1)

In [20]:
notes_df["appearanceDeathDiff"] = notes_df["firstAppearanceDate"] - notes_df["deathDate"]

In [21]:
notes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              279 non-null    object
 1   countryAbbr          279 non-null    object
 2   currencyName         279 non-null    object
 3   name                 279 non-null    object
 4   gender               279 non-null    object
 5   billCount            279 non-null    float64
 6   profession           279 non-null    object
 7   knownForBeingFirst   279 non-null    object
 8   currentBillValue     279 non-null    int64
 9   propTotalBills       59 non-null     float64
 10  firstAppearanceDate  279 non-null    int64
 11  deathDate            278 non-null    Int64
 12  appearanceDeathDiff  278 non-null    Int64
 13  comments             119 non-null    object
 14  hoverText            89 non-null     object
 15  hasPortrait          279 non-null    bool
 16  id                   279 non-null    object
dtypes: Int64(2), bool(1), float64(2), int64(2), object(10)
memory usage: 35.8+ KB

In [22]:
notes_df.head()

,country,countryAbbr,currencyName,name,gender,billCount,profession,knownForBeingFirst,currentBillValue,propTotalBills,firstAppearanceDate,deathDate,appearanceDeathDiff,comments,hoverText,hasPortrait,id
0,Argentina,ARS,Argentinian Peso,Eva Perón,F,1.0,Activist,No,100,NaN,2012,1952,60,NaN,NaN,True,ARS_Evita
1,Argentina,ARS,Argentinian Peso,Julio Argentino Roca,M,1.0,Head of Gov't,No,100,NaN,1988,1914,74,NaN,NaN,True,ARS_Argentino
2,Argentina,ARS,Argentinian Peso,Domingo Faustino Sarmiento,M,1.0,Head of Gov't,No,50,NaN,1999,1888,111,NaN,NaN,True,ARS_Domingo
3,Argentina,ARS,Argentinian Peso,Juan Manuel de Rosas,M,1.0,Politician,No,20,NaN,1992,1877,115,NaN,NaN,True,ARS_Rosas
4,Argentina,ARS,Argentinian Peso,Manuel Belgrano,M,1.0,Founder,Yes,10,NaN,1970,1820,150,Came up with the first Argentine flag.,Designed first Argentine flag,True,ARS_Belgrano